# Generated by Django 4.2.11 on 2024-07-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowtoTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='P_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='T_receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_name', models.CharField(max_length=100)),
                ('tr_contact', models.IntegerField(blank=True, null=True)),
                ('tr_location', models.CharField(blank=True, max_length=100, null=True)),
                ('tr_photo_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('tr_howtocontact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.howtotrack')),
            ],
        ),
        migrations.CreateModel(
            name='T_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_name', models.CharField(max_length=100)),
                ('td_contact', models.IntegerField(blank=True, null=True)),
                ('td_location', models.CharField(blank=True, max_length=100, null=True)),
                ('td_photo_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('td_howtocontact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.howtotrack')),
            ],
        ),
        migrations.CreateModel(
            name='P_reciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_name', models.CharField(blank=True, max_length=100, null=True)),
                ('R_regno', models.IntegerField(blank=True, null=True)),
                ('R_photo_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('R_contact', models.IntegerField(blank=True, null=True)),
                ('R_description', models.CharField(blank=True, max_length=600, null=True)),
                ('R_location', models.CharField(blank=True, max_length=100, null=True)),
                ('R_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.p_category')),
            ],
        ),
        migrations.CreateModel(
            name='P_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_name', models.CharField(blank=True, max_length=100, null=True)),
                ('D_location', models.CharField(blank=True, max_length=100, null=True)),
                ('D_regno', models.IntegerField(blank=True, null=True)),
                ('D_photo_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('D_contact', models.IntegerField(blank=True, null=True)),
                ('D_description', models.CharField(blank=True, max_length=600, null=True)),
                ('D_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.p_category')),
            ],
        ),
    ]
