# Generated by Django 5.0.3 on 2024-08-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uplift'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_donor',
            name='D_contactcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p_donor',
            name='D_emailcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p_receiver',
            name='R_contactcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p_receiver',
            name='R_emailcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_donor',
            name='td_contactcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_donor',
            name='td_emailcheckbox',
            field=models.BooleanField(default=False),
        ),
    ]
